//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: PlayerSubmissionData.proto

@kotlin.jvm.JvmName("-initializeplayerSubmissionData")
inline fun playerSubmissionData(block: PlayerSubmissionDataKt.Dsl.() -> kotlin.Unit): PlayerSubmissionDataOuterClass.PlayerSubmissionData =
  PlayerSubmissionDataKt.Dsl._create(PlayerSubmissionDataOuterClass.PlayerSubmissionData.newBuilder()).apply { block() }._build()
object PlayerSubmissionDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: PlayerSubmissionDataOuterClass.PlayerSubmissionData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: PlayerSubmissionDataOuterClass.PlayerSubmissionData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): PlayerSubmissionDataOuterClass.PlayerSubmissionData = _builder.build()

    /**
     * <code>int32 score = 1;</code>
     */
    var score: kotlin.Int
      @JvmName("getScore")
      get() = _builder.getScore()
      @JvmName("setScore")
      set(value) {
        _builder.setScore(value)
      }
    /**
     * <code>int32 score = 1;</code>
     */
    fun clearScore() {
      _builder.clearScore()
    }

    /**
     * <code>string name = 2;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>string ip = 3;</code>
     */
    var ip: kotlin.String
      @JvmName("getIp")
      get() = _builder.getIp()
      @JvmName("setIp")
      set(value) {
        _builder.setIp(value)
      }
    /**
     * <code>string ip = 3;</code>
     */
    fun clearIp() {
      _builder.clearIp()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class WordsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string words = 4;</code>
     * @return A list containing the words.
     */
     val words: com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getWordsList()
      )
    /**
     * <code>repeated string words = 4;</code>
     * @param value The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWords")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>.add(value: kotlin.String) {
      _builder.addWords(value)
    }
    /**
     * <code>repeated string words = 4;</code>
     * @param value The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWords")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string words = 4;</code>
     * @param values The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWords")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllWords(values)
    }
    /**
     * <code>repeated string words = 4;</code>
     * @param values The words to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWords")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string words = 4;</code>
     * @param index The index to set the value at.
     * @param value The words to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWords")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setWords(index, value)
    }/**
     * <code>repeated string words = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWords")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, WordsProxy>.clear() {
      _builder.clearWords()
    }
    /**
     * <code>bytes checksum = 5;</code>
     */
    var checksum: com.google.protobuf.ByteString
      @JvmName("getChecksum")
      get() = _builder.getChecksum()
      @JvmName("setChecksum")
      set(value) {
        _builder.setChecksum(value)
      }
    /**
     * <code>bytes checksum = 5;</code>
     */
    fun clearChecksum() {
      _builder.clearChecksum()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun PlayerSubmissionDataOuterClass.PlayerSubmissionData.copy(block: PlayerSubmissionDataKt.Dsl.() -> kotlin.Unit): PlayerSubmissionDataOuterClass.PlayerSubmissionData =
  PlayerSubmissionDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

