// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerSubmissionData.proto

public final class PlayerSubmissionDataOuterClass {
  private PlayerSubmissionDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerSubmissionDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerSubmissionData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 score = 1;</code>
     * @return The score.
     */
    int getScore();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>repeated string words = 4;</code>
     * @return A list containing the words.
     */
    java.util.List<java.lang.String>
        getWordsList();
    /**
     * <code>repeated string words = 4;</code>
     * @return The count of words.
     */
    int getWordsCount();
    /**
     * <code>repeated string words = 4;</code>
     * @param index The index of the element to return.
     * @return The words at the given index.
     */
    java.lang.String getWords(int index);
    /**
     * <code>repeated string words = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the words at the given index.
     */
    com.google.protobuf.ByteString
        getWordsBytes(int index);

    /**
     * <code>bytes checksum = 5;</code>
     * @return The checksum.
     */
    com.google.protobuf.ByteString getChecksum();
  }
  /**
   * Protobuf type {@code PlayerSubmissionData}
   */
  public static final class PlayerSubmissionData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerSubmissionData)
      PlayerSubmissionDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerSubmissionData.newBuilder() to construct.
    private PlayerSubmissionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerSubmissionData() {
      name_ = "";
      ip_ = "";
      words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      checksum_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerSubmissionData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerSubmissionData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              score_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                words_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              words_.add(s);
              break;
            }
            case 42: {

              checksum_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          words_ = words_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerSubmissionDataOuterClass.internal_static_PlayerSubmissionData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerSubmissionDataOuterClass.internal_static_PlayerSubmissionData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlayerSubmissionDataOuterClass.PlayerSubmissionData.class, PlayerSubmissionDataOuterClass.PlayerSubmissionData.Builder.class);
    }

    public static final int SCORE_FIELD_NUMBER = 1;
    private int score_;
    /**
     * <code>int32 score = 1;</code>
     * @return The score.
     */
    @java.lang.Override
    public int getScore() {
      return score_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList words_;
    /**
     * <code>repeated string words = 4;</code>
     * @return A list containing the words.
     */
    public com.google.protobuf.ProtocolStringList
        getWordsList() {
      return words_;
    }
    /**
     * <code>repeated string words = 4;</code>
     * @return The count of words.
     */
    public int getWordsCount() {
      return words_.size();
    }
    /**
     * <code>repeated string words = 4;</code>
     * @param index The index of the element to return.
     * @return The words at the given index.
     */
    public java.lang.String getWords(int index) {
      return words_.get(index);
    }
    /**
     * <code>repeated string words = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the words at the given index.
     */
    public com.google.protobuf.ByteString
        getWordsBytes(int index) {
      return words_.getByteString(index);
    }

    public static final int CHECKSUM_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString checksum_;
    /**
     * <code>bytes checksum = 5;</code>
     * @return The checksum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChecksum() {
      return checksum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (score_ != 0) {
        output.writeInt32(1, score_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      for (int i = 0; i < words_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, words_.getRaw(i));
      }
      if (!checksum_.isEmpty()) {
        output.writeBytes(5, checksum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, score_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ip_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < words_.size(); i++) {
          dataSize += computeStringSizeNoTag(words_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getWordsList().size();
      }
      if (!checksum_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, checksum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlayerSubmissionDataOuterClass.PlayerSubmissionData)) {
        return super.equals(obj);
      }
      PlayerSubmissionDataOuterClass.PlayerSubmissionData other = (PlayerSubmissionDataOuterClass.PlayerSubmissionData) obj;

      if (getScore()
          != other.getScore()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (!getWordsList()
          .equals(other.getWordsList())) return false;
      if (!getChecksum()
          .equals(other.getChecksum())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getScore();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      if (getWordsCount() > 0) {
        hash = (37 * hash) + WORDS_FIELD_NUMBER;
        hash = (53 * hash) + getWordsList().hashCode();
      }
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlayerSubmissionDataOuterClass.PlayerSubmissionData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerSubmissionData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerSubmissionData)
        PlayerSubmissionDataOuterClass.PlayerSubmissionDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlayerSubmissionDataOuterClass.internal_static_PlayerSubmissionData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlayerSubmissionDataOuterClass.internal_static_PlayerSubmissionData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlayerSubmissionDataOuterClass.PlayerSubmissionData.class, PlayerSubmissionDataOuterClass.PlayerSubmissionData.Builder.class);
      }

      // Construct using PlayerSubmissionDataOuterClass.PlayerSubmissionData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        score_ = 0;

        name_ = "";

        ip_ = "";

        words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        checksum_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlayerSubmissionDataOuterClass.internal_static_PlayerSubmissionData_descriptor;
      }

      @java.lang.Override
      public PlayerSubmissionDataOuterClass.PlayerSubmissionData getDefaultInstanceForType() {
        return PlayerSubmissionDataOuterClass.PlayerSubmissionData.getDefaultInstance();
      }

      @java.lang.Override
      public PlayerSubmissionDataOuterClass.PlayerSubmissionData build() {
        PlayerSubmissionDataOuterClass.PlayerSubmissionData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PlayerSubmissionDataOuterClass.PlayerSubmissionData buildPartial() {
        PlayerSubmissionDataOuterClass.PlayerSubmissionData result = new PlayerSubmissionDataOuterClass.PlayerSubmissionData(this);
        int from_bitField0_ = bitField0_;
        result.score_ = score_;
        result.name_ = name_;
        result.ip_ = ip_;
        if (((bitField0_ & 0x00000001) != 0)) {
          words_ = words_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.words_ = words_;
        result.checksum_ = checksum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlayerSubmissionDataOuterClass.PlayerSubmissionData) {
          return mergeFrom((PlayerSubmissionDataOuterClass.PlayerSubmissionData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlayerSubmissionDataOuterClass.PlayerSubmissionData other) {
        if (other == PlayerSubmissionDataOuterClass.PlayerSubmissionData.getDefaultInstance()) return this;
        if (other.getScore() != 0) {
          setScore(other.getScore());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.words_.isEmpty()) {
          if (words_.isEmpty()) {
            words_ = other.words_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWordsIsMutable();
            words_.addAll(other.words_);
          }
          onChanged();
        }
        if (other.getChecksum() != com.google.protobuf.ByteString.EMPTY) {
          setChecksum(other.getChecksum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlayerSubmissionDataOuterClass.PlayerSubmissionData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlayerSubmissionDataOuterClass.PlayerSubmissionData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int score_ ;
      /**
       * <code>int32 score = 1;</code>
       * @return The score.
       */
      @java.lang.Override
      public int getScore() {
        return score_;
      }
      /**
       * <code>int32 score = 1;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(int value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 score = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWordsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          words_ = new com.google.protobuf.LazyStringArrayList(words_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string words = 4;</code>
       * @return A list containing the words.
       */
      public com.google.protobuf.ProtocolStringList
          getWordsList() {
        return words_.getUnmodifiableView();
      }
      /**
       * <code>repeated string words = 4;</code>
       * @return The count of words.
       */
      public int getWordsCount() {
        return words_.size();
      }
      /**
       * <code>repeated string words = 4;</code>
       * @param index The index of the element to return.
       * @return The words at the given index.
       */
      public java.lang.String getWords(int index) {
        return words_.get(index);
      }
      /**
       * <code>repeated string words = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the words at the given index.
       */
      public com.google.protobuf.ByteString
          getWordsBytes(int index) {
        return words_.getByteString(index);
      }
      /**
       * <code>repeated string words = 4;</code>
       * @param index The index to set the value at.
       * @param value The words to set.
       * @return This builder for chaining.
       */
      public Builder setWords(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsIsMutable();
        words_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 4;</code>
       * @param value The words to add.
       * @return This builder for chaining.
       */
      public Builder addWords(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsIsMutable();
        words_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 4;</code>
       * @param values The words to add.
       * @return This builder for chaining.
       */
      public Builder addAllWords(
          java.lang.Iterable<java.lang.String> values) {
        ensureWordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, words_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWords() {
        words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string words = 4;</code>
       * @param value The bytes of the words to add.
       * @return This builder for chaining.
       */
      public Builder addWordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureWordsIsMutable();
        words_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString checksum_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes checksum = 5;</code>
       * @return The checksum.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChecksum() {
        return checksum_;
      }
      /**
       * <code>bytes checksum = 5;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes checksum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {
        
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerSubmissionData)
    }

    // @@protoc_insertion_point(class_scope:PlayerSubmissionData)
    private static final PlayerSubmissionDataOuterClass.PlayerSubmissionData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlayerSubmissionDataOuterClass.PlayerSubmissionData();
    }

    public static PlayerSubmissionDataOuterClass.PlayerSubmissionData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerSubmissionData>
        PARSER = new com.google.protobuf.AbstractParser<PlayerSubmissionData>() {
      @java.lang.Override
      public PlayerSubmissionData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerSubmissionData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerSubmissionData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerSubmissionData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PlayerSubmissionDataOuterClass.PlayerSubmissionData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerSubmissionData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerSubmissionData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032PlayerSubmissionData.proto\"`\n\024PlayerSu" +
      "bmissionData\022\r\n\005score\030\001 \001(\005\022\014\n\004name\030\002 \001(" +
      "\t\022\n\n\002ip\030\003 \001(\t\022\r\n\005words\030\004 \003(\t\022\020\n\010checksum" +
      "\030\005 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlayerSubmissionData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerSubmissionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerSubmissionData_descriptor,
        new java.lang.String[] { "Score", "Name", "Ip", "Words", "Checksum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
